<?xml version="1.0"?>
<package format="3">
  <name>metro_description</name>
  <version>0.1.0</version>
  <description>Robot descriptions and model assets for the subway patrol robot.</description>
  <maintainer email="jo0625@users.noreply.github.com">jo0625</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>gazebo_plugins</exec_depend>
  <exec_depend>gazebo_ros2_control</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>position_controllers</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>urdf</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
